version: '3.7'

services:
  sql_server_local:
    container_name: postgres_server
    image: postgres
    environment:  
        POSTGRES_PASSWORD: senhaDoPostgressCode123
    ports:
        - '1433:1433'
        - '5432:5432'
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080